env:
  browser: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
  - jest
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle:
    - error
    - allow: ['__filename', '__dirname']
overrides:
  - files:
      - __tests__/**/*
    plugins:
      - jest
    env:
      jest/globals: true
